<?php

/**
 * Implements hook_field_schema().
 */
function rgb_field_field_schema($field) {

  $columns = [
    'rgb' => [
      'type' => 'varchar',
      'length' => 6,
      'not null' => TRUE,
    ],
    'label' => [
      'type' => 'varchar',
      'length' => 128,
      'not null' => FALSE,
    ],
  ];

  $indexes = [
    'rgb' => ['rgb'],
  ];

  return [
    'columns' => $columns,
    'indexes' => $indexes,
  ];
}
